### PR TITLE
Extended Item Functionality

### PR DESCRIPTION
**Pull request by MatKarnicki**
# Extended Item Functionality 
* Add wrappers for stat increase functions
* Implement stat functionality for items
* Add toggable Item Description UI element

### CODE REVIEW

**Comment by SimiCoffee** [comment]
Looks good to me

**Review by hparzychrec — APPROVED** [review]
Good job :heart:

**Review by SimiCoffee — APPROVED** [review]
Looks good to me

**Review by lminasiewicz — APPROVED** [review]
WHO THE HELL IS FRANKE

**Pull request merged**
